#!/bin/bash
set -eu

## Install the default config if none was provided
if [ ! -e /etc/holland/holland.conf ]; then
	echo 'Creating default holland.conf'
	cp /etc/holland.orig/holland.conf /etc/holland/holland.conf
fi

if [ ! -d /etc/holland/backupsets ]; then
	echo 'Creating default backupsets'
	cp -r /etc/holland.orig/backupsets /etc/holland/backupsets
fi

if [ ! -d /etc/holland/providers ]; then
	echo 'Creating default providers'
	cp -r /etc/holland.orig/providers /etc/holland/providers
fi

## Change the default config to log to stdout rather than a log file
sed -i 's/\/var\/log\/holland\/holland\.log/\/dev\/stdout/g' /etc/holland/holland.conf

## Override default crontab if job config is specified
CROND_JOB_CONFIG="${CROND_JOB_CONFIG:-}"
if [[ -n "${CROND_JOB_CONFIG}" ]]; then
    echo "${CROND_JOB_CONFIG}" | base64 -d > /etc/cron.d/holland
fi

## Start crond to run holland on schedule
exec "$@"
